-- ============================================================
-- Datos de ejemplo (prendas) para que la demo no se vea vacía.
-- Modelos basados en el catálogo real de Roly (marca que distribuye
-- Rodmen Rotulaciones), con varias tallas y colores por modelo para
-- poder probar el filtrado de la vista de modelos/variantes.
-- Ejecutar UNA SOLA VEZ en el SQL Editor de Supabase, después de
-- schema.sql. (No está pensado para correr dos veces, duplicaría
-- los productos.)
-- ============================================================

-- 1. Crear los productos (la cantidad se fija en 0 aquí; el paso 2 la completa
--    mediante un movimiento de entrada, igual que haría un usuario real)
insert into products (category_id, model, size, color, quantity)
select c.id, v.model, v.size, v.color, 0
from (values
  -- Camisetas
  ('Camisetas', 'Básica Cuello Redondo', 'S',  'Blanco'),
  ('Camisetas', 'Básica Cuello Redondo', 'M',  'Negro'),
  ('Camisetas', 'Básica Cuello Redondo', 'L',  'Gris'),
  ('Camisetas', 'Básica Cuello Redondo', 'XL', 'Azul Marino'),
  ('Camisetas', 'Básica Cuello Redondo', 'M',  'Rojo'),
  ('Camisetas', 'Manga Larga Térmica',   'S',  'Blanco'),
  ('Camisetas', 'Manga Larga Térmica',   'M',  'Negro'),
  ('Camisetas', 'Manga Larga Térmica',   'L',  'Gris'),
  ('Camisetas', 'Manga Larga Térmica',   'XL', 'Azul Marino'),
  ('Camisetas', 'Beagle',                'S',  'Blanco'),
  ('Camisetas', 'Beagle',                'M',  'Blanco'),
  ('Camisetas', 'Beagle',                'M',  'Negro'),
  ('Camisetas', 'Beagle',                'L',  'Negro'),
  ('Camisetas', 'Beagle',                'L',  'Rojo'),
  ('Camisetas', 'Beagle',                'XL', 'Azul Royal'),
  ('Camisetas', 'Atomic',                'S',  'Blanco'),
  ('Camisetas', 'Atomic',                'M',  'Gris Vigoré'),
  ('Camisetas', 'Atomic',                'M',  'Rojo'),
  ('Camisetas', 'Atomic',                'L',  'Negro'),
  ('Camisetas', 'Atomic',                'XL', 'Azul Marino'),
  ('Camisetas', 'Braco',                 'S',  'Negro'),
  ('Camisetas', 'Braco',                 'M',  'Negro'),
  ('Camisetas', 'Braco',                 'L',  'Blanco'),
  ('Camisetas', 'Braco',                 'L',  'Gris'),
  ('Camisetas', 'Braco',                 'XL', 'Verde Bosque'),
  ('Camisetas', 'Stafford',              'S',  'Blanco'),
  ('Camisetas', 'Stafford',              'M',  'Negro'),
  ('Camisetas', 'Stafford',              'L',  'Gris'),
  ('Camisetas', 'Stafford',              'XL', 'Azul Marino'),

  -- Sudaderas
  ('Sudaderas', 'Capucha Classic', 'S',  'Negro'),
  ('Sudaderas', 'Capucha Classic', 'M',  'Verde Bosque'),
  ('Sudaderas', 'Capucha Classic', 'L',  'Azul Marino'),
  ('Sudaderas', 'Capucha Classic', 'XL', 'Gris'),
  ('Sudaderas', 'Urban',           'S',  'Negro'),
  ('Sudaderas', 'Urban',           'M',  'Gris'),
  ('Sudaderas', 'Urban',           'M',  'Rojo'),
  ('Sudaderas', 'Urban',           'L',  'Negro'),
  ('Sudaderas', 'Urban',           'XL', 'Azul Marino'),
  ('Sudaderas', 'Aneto',           'S',  'Negro'),
  ('Sudaderas', 'Aneto',           'M',  'Gris Vigoré'),
  ('Sudaderas', 'Aneto',           'M',  'Negro'),
  ('Sudaderas', 'Aneto',           'L',  'Rojo'),
  ('Sudaderas', 'Aneto',           'XL', 'Azul Marino'),
  ('Sudaderas', 'Veleta',          'S',  'Gris'),
  ('Sudaderas', 'Veleta',          'M',  'Negro'),
  ('Sudaderas', 'Veleta',          'L',  'Azul Marino'),
  ('Sudaderas', 'Veleta',          'XL', 'Negro'),

  -- Pantalones
  ('Pantalones', 'Cargo Multibolsillo', 'S',  'Gris'),
  ('Pantalones', 'Cargo Multibolsillo', 'M',  'Caqui'),
  ('Pantalones', 'Cargo Multibolsillo', 'L',  'Negro'),
  ('Pantalones', 'Cargo Multibolsillo', 'XL', 'Azul Marino'),
  ('Pantalones', 'Daily',               'S',  'Negro'),
  ('Pantalones', 'Daily',               'M',  'Negro'),
  ('Pantalones', 'Daily',               'M',  'Caqui'),
  ('Pantalones', 'Daily',               'L',  'Gris'),
  ('Pantalones', 'Daily',               'XL', 'Azul Marino'),
  ('Pantalones', 'Daily Stretch',       'S',  'Negro'),
  ('Pantalones', 'Daily Stretch',       'M',  'Gris'),
  ('Pantalones', 'Daily Stretch',       'L',  'Negro'),
  ('Pantalones', 'Daily Stretch',       'XL', 'Azul Marino'),
  ('Pantalones', 'Soan',                'S',  'Gris'),
  ('Pantalones', 'Soan',                'M',  'Caqui'),
  ('Pantalones', 'Soan',                'L',  'Negro'),
  ('Pantalones', 'Soan',                'XL', 'Caqui'),

  -- Polos
  ('Polos', 'Piqué Premium', 'S',  'Negro'),
  ('Polos', 'Piqué Premium', 'M',  'Blanco'),
  ('Polos', 'Piqué Premium', 'L',  'Verde Salvia'),
  ('Polos', 'Piqué Premium', 'XL', 'Azul Marino'),
  ('Polos', 'Monzha',        'S',  'Blanco'),
  ('Polos', 'Monzha',        'M',  'Negro'),
  ('Polos', 'Monzha',        'M',  'Rojo'),
  ('Polos', 'Monzha',        'L',  'Azul Marino'),
  ('Polos', 'Monzha',        'XL', 'Blanco'),
  ('Polos', 'Pegaso',        'S',  'Azul Marino'),
  ('Polos', 'Pegaso',        'M',  'Blanco'),
  ('Polos', 'Pegaso',        'L',  'Negro'),
  ('Polos', 'Pegaso',        'XL', 'Blanco'),
  ('Polos', 'Prince',        'S',  'Verde Bosque'),
  ('Polos', 'Prince',        'M',  'Negro'),
  ('Polos', 'Prince',        'L',  'Blanco'),
  ('Polos', 'Prince',        'XL', 'Negro'),

  -- Chaquetas
  ('Chaquetas', 'Softshell Impermeable', 'S',  'Azul Marino'),
  ('Chaquetas', 'Softshell Impermeable', 'M',  'Negro'),
  ('Chaquetas', 'Softshell Impermeable', 'L',  'Gris Oscuro'),
  ('Chaquetas', 'Softshell Impermeable', 'XL', 'Negro'),
  ('Chaquetas', 'Antares',               'S',  'Negro'),
  ('Chaquetas', 'Antares',               'M',  'Negro'),
  ('Chaquetas', 'Antares',               'L',  'Gris Oscuro'),
  ('Chaquetas', 'Antares',               'XL', 'Azul Marino'),
  ('Chaquetas', 'Altair',                'S',  'Negro'),
  ('Chaquetas', 'Altair',                'M',  'Azul Marino'),
  ('Chaquetas', 'Altair',                'L',  'Negro'),
  ('Chaquetas', 'Altair',                'XL', 'Gris Oscuro'),
  ('Chaquetas', 'Naos',                  'S',  'Negro'),
  ('Chaquetas', 'Naos',                  'M',  'Negro'),
  ('Chaquetas', 'Naos',                  'L',  'Amarillo Flúor'),
  ('Chaquetas', 'Naos',                  'XL', 'Amarillo Flúor')
) as v(category, model, size, color)
join categories c on c.name = v.category;

-- 2. Registrar el stock inicial de cada producto (el trigger automático
--    de stock_movements se encarga de sumarlo a products.quantity)
insert into stock_movements (product_id, type, quantity, note)
select p.id, 'entrada', v.qty, 'Stock inicial demo'
from products p
join (values
  ('Básica Cuello Redondo', 'S', 'Blanco', 18),
  ('Básica Cuello Redondo', 'M', 'Negro', 32),
  ('Básica Cuello Redondo', 'L', 'Gris', 13),
  ('Básica Cuello Redondo', 'XL', 'Azul Marino', 9),
  ('Básica Cuello Redondo', 'M', 'Rojo', 11),
  ('Manga Larga Térmica', 'S', 'Blanco', 10),
  ('Manga Larga Térmica', 'M', 'Negro', 14),
  ('Manga Larga Térmica', 'L', 'Gris', 14),
  ('Manga Larga Térmica', 'XL', 'Azul Marino', 7),
  ('Beagle', 'S', 'Blanco', 24),
  ('Beagle', 'M', 'Blanco', 16),
  ('Beagle', 'M', 'Negro', 30),
  ('Beagle', 'L', 'Negro', 13),
  ('Beagle', 'L', 'Rojo', 18),
  ('Beagle', 'XL', 'Azul Royal', 12),
  ('Atomic', 'S', 'Blanco', 20),
  ('Atomic', 'M', 'Gris Vigoré', 15),
  ('Atomic', 'M', 'Rojo', 12),
  ('Atomic', 'L', 'Negro', 10),
  ('Atomic', 'XL', 'Azul Marino', 8),
  ('Braco', 'S', 'Negro', 9),
  ('Braco', 'M', 'Negro', 22),
  ('Braco', 'L', 'Blanco', 14),
  ('Braco', 'L', 'Gris', 10),
  ('Braco', 'XL', 'Verde Bosque', 8),
  ('Stafford', 'S', 'Blanco', 16),
  ('Stafford', 'M', 'Negro', 19),
  ('Stafford', 'L', 'Gris', 11),
  ('Stafford', 'XL', 'Azul Marino', 7),

  ('Capucha Classic', 'S', 'Negro', 9),
  ('Capucha Classic', 'M', 'Verde Bosque', 20),
  ('Capucha Classic', 'L', 'Azul Marino', 12),
  ('Capucha Classic', 'XL', 'Gris', 6),
  ('Urban', 'S', 'Negro', 8),
  ('Urban', 'M', 'Gris', 17),
  ('Urban', 'M', 'Rojo', 7),
  ('Urban', 'L', 'Negro', 21),
  ('Urban', 'XL', 'Azul Marino', 9),
  ('Aneto', 'S', 'Negro', 13),
  ('Aneto', 'M', 'Gris Vigoré', 11),
  ('Aneto', 'M', 'Negro', 10),
  ('Aneto', 'L', 'Rojo', 7),
  ('Aneto', 'XL', 'Azul Marino', 6),
  ('Veleta', 'S', 'Gris', 9),
  ('Veleta', 'M', 'Negro', 14),
  ('Veleta', 'L', 'Azul Marino', 10),
  ('Veleta', 'XL', 'Negro', 7),

  ('Cargo Multibolsillo', 'S', 'Gris', 8),
  ('Cargo Multibolsillo', 'M', 'Caqui', 16),
  ('Cargo Multibolsillo', 'L', 'Negro', 9),
  ('Cargo Multibolsillo', 'XL', 'Azul Marino', 6),
  ('Daily', 'S', 'Negro', 9),
  ('Daily', 'M', 'Negro', 18),
  ('Daily', 'M', 'Caqui', 11),
  ('Daily', 'L', 'Gris', 12),
  ('Daily', 'XL', 'Azul Marino', 9),
  ('Daily Stretch', 'S', 'Negro', 11),
  ('Daily Stretch', 'M', 'Gris', 14),
  ('Daily Stretch', 'L', 'Negro', 10),
  ('Daily Stretch', 'XL', 'Azul Marino', 7),
  ('Soan', 'S', 'Gris', 8),
  ('Soan', 'M', 'Caqui', 16),
  ('Soan', 'L', 'Negro', 8),
  ('Soan', 'XL', 'Caqui', 9),

  ('Piqué Premium', 'S', 'Negro', 10),
  ('Piqué Premium', 'M', 'Blanco', 22),
  ('Piqué Premium', 'L', 'Verde Salvia', 15),
  ('Piqué Premium', 'XL', 'Azul Marino', 8),
  ('Monzha', 'S', 'Blanco', 20),
  ('Monzha', 'M', 'Negro', 24),
  ('Monzha', 'M', 'Rojo', 11),
  ('Monzha', 'L', 'Azul Marino', 13),
  ('Monzha', 'XL', 'Blanco', 9),
  ('Pegaso', 'S', 'Azul Marino', 7),
  ('Pegaso', 'M', 'Blanco', 15),
  ('Pegaso', 'L', 'Negro', 12),
  ('Pegaso', 'XL', 'Blanco', 9),
  ('Prince', 'S', 'Verde Bosque', 9),
  ('Prince', 'M', 'Negro', 17),
  ('Prince', 'L', 'Blanco', 8),
  ('Prince', 'XL', 'Negro', 10),

  ('Softshell Impermeable', 'S', 'Azul Marino', 6),
  ('Softshell Impermeable', 'M', 'Negro', 7),
  ('Softshell Impermeable', 'L', 'Gris Oscuro', 5),
  ('Softshell Impermeable', 'XL', 'Negro', 5),
  ('Antares', 'S', 'Negro', 5),
  ('Antares', 'M', 'Negro', 10),
  ('Antares', 'L', 'Gris Oscuro', 7),
  ('Antares', 'XL', 'Azul Marino', 7),
  ('Altair', 'S', 'Negro', 6),
  ('Altair', 'M', 'Azul Marino', 9),
  ('Altair', 'L', 'Negro', 6),
  ('Altair', 'XL', 'Gris Oscuro', 4),
  ('Naos', 'S', 'Negro', 4),
  ('Naos', 'M', 'Negro', 5),
  ('Naos', 'L', 'Amarillo Flúor', 11),
  ('Naos', 'XL', 'Amarillo Flúor', 6)
) as v(model, size, color, qty)
  on p.model = v.model and p.size = v.size and p.color = v.color;
